FROM node:14 as builder

RUN npm install -g @angular/cli

COPY . /usr/front
WORKDIR /usr/front

RUN npm install
RUN npm run build --prod

#CMD [ "ng test" ]
FROM nginx 
COPY --from=builder /usr/front/dist/tlcfront/ /usr/share/nginx/html
